language: python
python:
  - "3.4"
  - "3.5"

sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y debhelper dput quilt sbuild schroot sudo

script:
  - nosetests --version
  - nosetests --plugins
  - pip freeze
  - nosetests -v
