#!/bin/bash

# Copyright © 2009 Stefano Zacchiroli <zack@upsilon.cc>
# Copyright © 2015 Andrew Stone <a@stoney.io>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] ; then
    echo "Usage: sign-remote KEY HOSTNAME REPO_BASE"
    exit 2
fi

tmp=`mktemp -d`
trap "rm -rf $tmp" EXIT
signed=""

cd $tmp

echo "I: retrieving files to sign from remote host ..."
ssh -C "$2" "tar -cf - \`find $3 -name Release\`" | tar -xf -

echo "I: signing retrieved files ..."
for f in `find . -type f`; do
	gpg -u "$1" --detach-sign --batch -o ./$f.gpg ./$f
	signed="$signed ./$f.gpg"
done

echo "I: sending back signed files ..."
tar -cf - $signed | ssh -C "$2" "tar -xf - -C /"
echo "I: signing done"
